* Model 
\begin{equation}
\frac{dS}{dt} = -\beta_A \frac{S.A}{N} -\beta_I \frac{S.I}{N}
\end{equation}
\begin{equation}
    \frac{dL}{dt} = \beta_A \frac{S.A}{N} + \beta_I \frac{S.I}{N} - \theta_I L - \theta_A L
\end{equation}
\begin{equation}
    \frac{dI}{dt} = \theta_I L - \alpha_I I - \gamma_I I
\end{equation}
\begin{equation}
    \frac{dA}{dt} = \theta_A L - \alpha_A A 
\end{equation}
\begin{equation}
    \frac{dD}{dt} = \gamma_I I 
\end{equation}
\begin{equation}
    \frac{dR}{dt} = \alpha_I I + \alpha_A A
\end{equation}

where, S = Susceptible, L = Latent, I = Infected, A = Asymptomatic, R = Recovered and D = Dead.

* Network  
** Normal condition
  Categorizing interaction into different levels of physical interactions -> *Community Structure*
  The entries of the adjacency matrix is given by, 
\begin{equation}
    f(l,x)=e^{-lx}
\end{equation}  
  "l" denotes the level of interaction and "x" takes value from an uniform random number generator.
** Lockdown condition
   Higher level connections get hampered strongly.
\begin{equation}
f(c,ld,x)=e^{-c^{(ld+1)}x} 
\end{equation}

* SLIARD on network
Adj = Adjacency matrix
\Vec{S_i} = column matrix containing the SLIARD feature of the "i"th node.
The node-node coupling is present only in the rates of S and L.
\begin{equation}
    \frac{d\Vec{S_i}}{dt} = - \beta_{A} \Vec{S_i}\sum\limits_{j}(Adj)_{ij}\Vec{A_j} - \beta_{I} \Vec{S_i}\sum\limits_{j}(Adj)_{ij}\Vec{I_j}
\end{equation}

\begin{equation}
    \frac{d\Vec{L_i}}{dt} =  \beta_A \Vec{S_i}\sum\limits_{j}(Adj)_{ij}\Vec{A_j} + \beta_I \Vec{S_i}\sum\limits_{j}(Adj)_{ij}\Vec{I_j} - \theta_I\Vec{L_i} - \theta_A\Vec{L_i}
\end{equation}
